### ISSUE TITLE
Support for upload and download progress reporting

### ISSUE THREAD

**Issue by pieterclaerhout** [graymeta/stow#101]
It would be very nice to have a unified way to get upload and download progress. Any plans on adding this?

**Comment by matryer** [comment]
Great idea. I suppose you could do it by reading and counting the bytes read, then subtracting that from the size?

**Comment by dahernan** [comment]
Not sure if that is useful in this library, you can always track the progress wrapping the standard `io.Reader` or `io.Writer` or using a `TeeReader`.
Other option is this library https://github.com/bartmeuris/progressio (I didn't use before) that also does it for any `Reader` and `Writer`

**Comment by matryer** [comment]
I agree it should happen outside of this library. Stow returns `io.ReadCloser`, so any of those other options are available.
