### ISSUE TITLE
add doc.go to each implementation

### ISSUE THREAD

**Issue by matryer** [graymeta/stow#102]
Add a `doc.go` file to each implementation with a small summary of what the package provides.

E.g.

```go
// Package local provides a filesystem Location. Folders are containers, and 
// files are items.
package local
```

**Comment by piotrrojek** [comment]
The issue seems forgotten @Xercoy. I fixed that quickly, I hope you don't mind.

**Comment by Xercoy** [comment]
Discussed with @piotrrojek, did not forget, my contributions for this are more comprehensive. Will have a WIP up.
