### ISSUE TITLE
Add `context` support

### ISSUE THREAD

**Issue by piotrrojek** [graymeta/stow#103]
We should add `context` for cancellation and timeout support.

**Comment by matryer** [comment]
Which methods would be affected?

**Comment by matryer** [comment]
Do the underlying packages support it?

**Comment by matryer** [comment]
@dahernan @ernesto-jimenez What do you guys think of this? Should we do it to future proof the API even if it isn't fully implemented?

**Comment by dahernan** [comment]
I don't think it make sense to add it right now. We rely on the Reader and Writer for the long running operations so even if we pass context, you'll get back an interface without context

**Comment by matryer** [comment]
Yeah we may revisit this later.
