### ISSUE TITLE
Support local servers

### ISSUE THREAD

**Issue by gebi** [graymeta/stow#104]
I could not find a method to use a local s3 server, it would be very nice to have support also for local versions of eg. s3.

eg. minio.io, ceph/radosgw, ...

**Comment by matryer** [comment]
Is it not just configuration on the S3 server? If not, it should be.

**Comment by jasonhancock** [comment]
@matryer stow would need to support setting the s3 endpoint. For example, here's how to use the aws golang sdk with minio: https://docs.minio.io/docs/how-to-use-aws-sdk-for-go-with-minio-server
