### ISSUE TITLE
Consistency between different adapters

### ISSUE THREAD

**Issue by niels-s** [graymeta/stow#109]
I started to experiment with Stow and wanted to use the local file system adapter for testing.But I've noticed there are some small inconsistencies between the local file system and the Google Cloud Storage adapter.
I've included 2 snippets do demonstrate the issue. I'm not sure if this behaviour is done on purpose or not, fixing or changing this could potentially break other people's code.

This is the Google Cloud Storage example, you can see I don't prefix the path of `container.Put` or `container.Item` with the container name

```
func main() {
	creds := `{}`
	projectID := ""

	config := stow.ConfigMap{
		"json":       creds,
		"project_id": projectID,
	}

		location, err := stow.Dial(google.Kind, config)
	if err != nil {
		panic(err)
	}
	defer location.Close()

	cs, _,_ := location.Containers("", stow.CursorStart, 10)
	for _, c := range cs {
		fmt.Printf("%v -> %v\n", c.Name(), c.ID())
	}
	container, _ := location.Container("niels-test")
	contents := "This is a new file stored in the cloud"
	r := strings.NewReader(contents)
	size := int64(len(contents))

	item, _ := container.Put("user/nielsstevens/index.json", r, size, nil)
        fmt.Printf("%+v", item)

	result, _ := container.Item("user/nielsstevens/index.json")
	fmt.Printf("%+v", result)
}
```

But now when I try the same approach for local file system, you will see I need to prefix the `container.Item` and `container.Put` with the `config.Path` and the `container.Name` which is not the same for GCS Adapter.

```
func main() {
        config := stow.ConfigMap{
		"path":       "/tmp/",
	}

	location, _ := stow.Dial(local.Kind, config)
	defer location.Close()

	cs, _,_ := location.Containers("", stow.CursorStart, 10)
	for _, c := range cs {
		fmt.Printf("%v -> %v\n", c.Name(), c.ID())
	}
	container, _ := location.Container("niels-test")

	contents := "This is a new file stored in the cloud"
	r := strings.NewReader(contents)
	size := int64(len(contents))

	item, _ := container.Put("/tmp/niels-test/user/nielsstevens/index.json", r, size, nil)
        fmt.Printf("%+v", item)

	result, _ := container.Item("/tmp/niels-test/user/nielsstevens/index.json")
	fmt.Printf("%+v", result)
}
```

**Comment by matryer** [comment]
Good spot. Definitely a bug we should fix.

**Comment by piotrrojek** [comment]
@niels-s the problem I've spotted is that you're using `container.Name()` method, instead of `container.ID()` here:
```go
container, _ := location.Container("niels-test")
```

Where "niels-test" is `container.Name()` as I assume. Also, if you would check for errors, you would get "container not found" error.

Often, like in Google implementation, `container.Name()` and `container.ID()` are equal. But in `local` package it isn't the case.

Look here for correct implementation, please:
https://github.com/graymeta/stow/blob/fix-109/local/stow_test.go#L26-L77

RE @matryer: close issue?

**Comment by matryer** [comment]
@niels-s does that make sense? Do you think the docs need to be updated to make this clearer?

**Comment by niels-s** [comment]
@piotrrojek so according to the test you are referring to the solution would be to always iterate over all the containers, check if  `container.Name()` matches the container we want, obtain the ID and then fetch the container?

If my assumption is correct I find this quite a strange behaviour, even in case where `container.Name() != container.ID()` it would expect the name of the container to be sufficient to retrieve the container.

**Comment by piotrrojek** [comment]
@niels-s Imagine that you're browsing files on your computer. When you open Explorer/Finder you get list of all files/folders (that's iterating). You see names, but your computer uses whole path (inode on unixes) to access them. Also, in cloud blob storages you can easily imagine a scenario when you have for example 2 items with the same name that aren't the same (the IDs are different). Name is just an attribute, a metadata. That's why we're using IDs that are guaranteed to be different.

> the solution would be to always iterate over all the containers, check if container.Name() matches the container we want, obtain the ID and then fetch the container?

Well, if you know the ID beforehand, you can use that directly.

I think we should make that clearer in the docs that you have to access items by ID. @matryer

**Comment by matryer** [comment]
@niels-s instead of storing the container name, can you store the ID?

The argument is called `id` - e.g. in the `Item` method of the [Container interface](https://godoc.org/github.com/graymeta/stow#Container).

**Comment by piotrrojek** [comment]
Since @niels-s is no longer commenting, I'm closing this issue.

@niels-s if you have any more questions or doubts, please feel free to reach out to us!

**Comment by logic** [comment]
So, @neils-s may have disappeared, but I'm happy to continue this conversation. :) I would suggest that `local` container and item ID generation should be relative to their nearest containing component. A concrete example of what I'm suggesting, consider the following directory tree:

- `/filesystem/location/` (the physical path to our `location`; whatever we'd pass in to `path`)
  - `containerA/`
    - `itemA`
    - `tmp/itemB`
  - `containerB/`
    - `filler/itemA`
    - `itemB`

Today, `itemB` in `containerA` gets an `ID()` of `/filesystem/location/containerA/tmp/itemB`, and a `Name()` of `itemB`. I'm proposing that it's `ID()` instead be `tmp/itemB`. Similarly, the `ID()` for `containerA` is `/filesystem/location/containerA`; I propose changing that to simply `containerA`.

Two main reasons:
1. Information leakage. If I expose the full `ID()` to an external consumer (which I need to do, if I want to enable them to perform direct lookups of items, unless I come up with a local layer of indirection for these identifiers, which requires ensure coherency for the indirection layer; consider a web-based container/item browser consumed by a user in front of a web browser, for example), I'm exposing a lot more than just container and item layout, I'm also exposing the host system's filesystem layout. That's not ideal, and it's a special case I have to apply for the local provider.
2. Trimming these down such that references are relative to the outer container (containers relative to their location, items relative to their container) behaves more in line with other providers (I wouldn't expect an object's ID to be universally unique, only unique within their containing element).

Leaving `Name()` alone seems reasonable, but a quick survey suggests that there's no difference between `ID()` and `Name()` on any of the `Item` or `Container` implementation right now *except* local, making it the gratuitously different one here. :) Which seems to suggest that perhaps simply eliminating `Name()` from the API entirely might be the right thing to do?

**Comment by logic** [comment]
(I should add that I'm happy to put together a PR for the proposed behavior, if folks are amenable to it. I'm eventually going to want to do this with a locally-forked version of the local provider anyway, so I'm happy to help upstream.)

**Comment by matryer** [comment]
Honestly, I'd expect the API to work as @logic described. We don't want to leak any information, and `path` is a part of the configuration.

Re `Name` and `ID`:

* `ID` is meant to be something you can use to get an item, but
* `Name` should only be the leaf of a path, which is displayable etc.

If they're _always_ the same, then maybe we need to change `Name` implementations to not include additional path details. In which case, we could rename it to `DisplayName`

**Comment by matryer** [comment]
@logic @piotrrojek What do you guys think? Shall we push ahead and make a change here?

**Comment by sagikazarmark** [comment]
I've just tried the local adapter and honestly I was surprised that the ID is the full path, not a relative one. Currently I have to pass the base path to my code as well if I want to use the local adapter without always looping through all the containers.

I would expect that a relative path would be enough as an ID.

**Comment by matryer** [comment]
Agreed. @piotrrojek let's look at this tomorrow and see what we think.

**Comment by sagikazarmark** [comment]
Any news?
