### ISSUE TITLE
add support for seeking to a specific byte offset of an Item

### ISSUE THREAD

**Issue by jasonhancock** [graymeta/stow#118]
Given an Item, there are some use cases where I want to only download a portion of the file starting at the Nth byte.

**Comment by matryer** [comment]
Most of the underlying implementations provide io.Reader, not io.ReadSeeker - so this would be impossible without reading and throwing away the unwanted bytes; in which case, the user can already do that.

**Comment by matryer** [comment]
However, see https://github.com/graymeta/stow/pull/128
