### ISSUE TITLE
Various feature requests

### ISSUE THREAD

**Issue by TamalSaha** [graymeta/stow#124]
Hi,
Thanks for this wonderful abstraction lib. We are planning to use it for various parts in our code base.  But it is missing some features. You can see the list here: https://github.com/appscode/stow/issues

I wanted to see if you will be interested in accepting PR for those. One important thing is I would like to add these features on a provider by provider basis. And some features might not be possible in some providers. So, it will throw `unsupported` error.

**Comment by matryer** [comment]
We are definitely interested in getting that functionality in. We should open an issue for each in the Stow repo if possible.

For cases where things might not be supported, returning the error is one approach, another is to define a specific interface inside the implementation package which would let you check for that capability.

e.g. 

```
type Feature interface {
  DoFeature()
}

//...

func something() {

  if itemWithFeature, ok := item.(Feature); ok {
    // use itemWithFeature.DoFeature()
  }

}
```

**Comment by TamalSaha** [comment]
Yes. I am going to file separate pr / issues for each one (probably for each provider).

I feel error might be better, since some of these will be temporary as I work through them.

**Comment by TamalSaha** [comment]
I have filed 3 separate prs for each of the changes we would like to see.
