### ISSUE TITLE
Use vendoring

### ISSUE THREAD

**Issue by tamalsaha** [graymeta/stow#126]
Hi,
It has been my experience that various cloud providers libraries change their API from time to time. I have experienced those with Azure and AWS sdks. I saw that `make` uses go get to download dependencies. I think stow should vendor its dependencies. We would prefer https://github.com/Masterminds/glide for vendoring. What do you think?

**Comment by matryer** [comment]
I think the general rule is, vendor for commands, don't for packages. @dahernan Can you shed some light?

**Comment by tjj5036** [comment]
👍 for vendoring, it'd reduce issues like: https://github.com/graymeta/stow/issues/137
