### ISSUE TITLE
How do I determine container name from Item?

### ISSUE THREAD

**Issue by tamalsaha** [graymeta/stow#130]
If I just have an `Item`, how do I determine the container name?

**Comment by matryer** [comment]
In theory, the container name is encoded in the Stow URL but this isn't formal. Internally, we store the Stow URL along with Container ID and a Location ID (which is a local lookup of kind and config).

**Comment by matryer** [comment]
But look at this: https://github.com/graymeta/stow/blob/master/google/location.go#L108

It seems we could add a `location.ContainerByURL` because all implementations know how to get the container from the URL.

**Comment by matryer** [comment]
@TamalSaha Should we add `location.ContainerByURL`?

**Comment by TamalSaha** [comment]
@matryer that will be handy. Thanks!

**Comment by matryer** [comment]
But that doesn't necessarily help if you have the `Item`
