### ISSUE TITLE
Swift and Oracle folders uses same pkg

### ISSUE THREAD

**Issue by TamalSaha** [graymeta/stow#132]
Swift and Oracle folders uses same pkg `swift`. This makes it impossible to use them both from a dependent library. In fact I am curios, why do you need the separate copy for Oracle?

**Comment by matryer** [comment]
Oracle's Swift implementation was special. Why does it make it impossible to use them both? At GrayMeta, we use them both with no problem.

**Comment by TamalSaha** [comment]
Thanks @matryer .

Why does it make it impossible to use them both? -  actually there will be no problem. Not sure what I was thinking. :)
