### ISSUE TITLE
Return appropriate error message

### ISSUE THREAD

**Issue by aerokite** [graymeta/stow#136]
In some cases, stow always returns "not found" error ignoring actual error message. 

```
func (l *Location) Container(id string) (stow.Container, error) {
	_, err := l.client.Buckets.Get(id).Do()
	if err != nil {
		return nil, stow.ErrNotFound
	}
}
```
Here, whatever the error is, its always returning stow.ErrNotFound. So in log I can't detect actual reason for this error.

Can you return actual error message or some appropriate message?

**Comment by matryer** [comment]
Good catch. @piotrrojek?
