### ISSUE TITLE
Error compiling. Azure might have changed SDK

### ISSUE THREAD

**Issue by nikita-memsql** [graymeta/stow#137]
../github.com/graymeta/stow/azure/container.go:61: c.client.ListBlobs undefined (type *storage.BlobStorageClient has no field or method ListBlobs)
../github.com/graymeta/stow/azure/location.go:23: l.client.CreateContainer undefined (type *storage.BlobStorageClient has no field or method CreateContainer)
../github.com/graymeta/stow/azure/location.go:112: l.client.DeleteContainer undefined (type *storage.BlobStorageClient has no field or method DeleteContainer)

**Comment by matryer** [comment]
@piotrrojek Can you have a gander at this please?
