### ISSUE TITLE
how to remove s3:// prefix new file urls

### ISSUE THREAD

**Issue by tonyalaribe** [graymeta/stow#158]
My urls look like this: "s3://https://s3-us-west-2.amazonaws.com/test-past3/s2/filesxx/jjj44/6564482-png" which isnt a valid url, and i use the urls directly in the browser. How do i have the s3 prefix, and the prefix for other storage backends (google, swift, etc) ?

**Comment by tonyalaribe** [comment]
I think i understand now. The urls are stow specific urls. But how about getting a url that would work outside of the stow context?

**Comment by jasonhancock** [comment]
There have been a couple of other asks for getting public facing urls:

https://github.com/graymeta/stow/issues/213
https://github.com/graymeta/stow/issues/187

Something for us to consider. Closing this out in favor of the others.
