### ISSUE TITLE
Cut a v0.1.1 release 

### ISSUE THREAD

**Issue by EngHabu** [graymeta/stow#188]
0.1.0 was released in 2016... maybe time for a fresh cut? 
I try to use SemVer whenever possible... keeps updates cleaner..

**Comment by mattwilliamson** [comment]
Even worse it breaks go modules since there is no google directory for example

**Comment by EngHabu** [comment]
Pinging this... can somebody do that relatively soon? We are in the process of open sourcing a repo and I would like to release it with a version reference to make it easier to absorb fixes later?

**Comment by thecodeassassin** [comment]
Pinging this as well, i would love to use this with go modules

**Comment by jasonhancock** [comment]
we've added go module support and dropped a v0.2.3 release
