### ISSUE TITLE
In memory backend?

### ISSUE THREAD

**Issue by miekg** [graymeta/stow#206]
Is there any appetite for having an in memory backend for stow? This will help in unit testing and some other fluff that then doesn't require to cleanup afterwards.

**Comment by jsteenb2** [comment]
testing with a local stow isn't to bad, but having one in memory would make that bar even lower to clear. Go for it 👍, pun intended 😉

**Comment by jasonhancock** [comment]
In practice it's easier to just use the local adapter coupled with a temporary directory:


```
 	dir, err := ioutil.TempDir("", "")
	if err != nil {
		t.Fatal("unable to create dir:", err)
	}
	defer os.RemoveAll(dir)

	config := stow.ConfigMap{"path": dir}
	location, err := storage.Dial("local", config)

        .... your test code....
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [graymeta/stow] In memory backe..." ]
>In practice it's easier to just use the local adapter coupled with a temporary directory:
>
>
>```
> 	dir, err := ioutil.TempDir("", "")
>	if err != nil {
>		t.Fatal("unable to create dir:", err)
>	}
>	defer os.RemoveAll(dir)
>
>	config := stow.ConfigMap{"path": dir}
>	location, err := storage.Dial("local", config)
>
>        .... your test code....
>```

oh nice!

Thanks, that solve it for our use case.
