### ISSUE TITLE
Support presigned URLs

### ISSUE THREAD

**Issue by mapreal19** [graymeta/stow#213]
Will make sense if we support presigned URLs?

Examples:

- https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-presigned-urls.html
- https://cloud.google.com/storage/docs/access-control/signed-urls

**Comment by EngHabu** [comment]
I've implemented this issue in #255. Can somebody please review?

**Comment by EngHabu** [comment]
CC @jasonhancock @jasonsattler maybe?

**Comment by jasonhancock** [comment]
I no longer work for graymeta, sorry

**Comment by EngHabu** [comment]
Thanks @jasonhancock for getting back to me. 

Increasing the blast radius: @matryer, @dahernan, @Xercoy, @ernesto-jimenez, @piotrrojek

Any chances of merging this soon?

**Comment by jasonhancock** [comment]
None of those people work for graymeta anymore either. I'm afraid the chances of getting any traction on this are probably nil

**Comment by EngHabu** [comment]
Ic.. I forked and renamed the module at https://gitHub.com/flyteorg/stow. Will proceed with that for the foreseeable future..

Thank you for your responses
