### ISSUE TITLE
implementation: Backblaze B2

### ISSUE THREAD

**Issue by jasonhancock** [graymeta/stow#37]
I was looking into implementing a Backblaze B2 backend for Stow. There are some limitations:
- Only returns a SHA1 checksum (https://www.backblaze.com/b2/docs/b2_get_file_info.html), not MD5. Might need to rename Item.MD5() to Item.Hash() and have it return the checksum + a string representing the type of hash. Or maybe just `backend.HashType` flag that could be set in each backend implementation.
- B2 doesn't support listing files or buckets with a prefix. Wondering if we should implement some sort of "SupportsFeature" type of booleans to each implementation (example `b2.SupportsPrefixes`) which could then be used in the test suite to only test things like prefixes on backends that support it. Adding the prefix support ourselves would be easy for buckets, but less so for files (not impossible, just a bit of work to identify the logic).

**Comment by liilac** [comment]
What's the current state of this?  Is there any current work on a Backblaze B2 implementation?

I'm interested in using B2 with stow, and would be interested in writing an implementation if no one else is.

What would be required on top of #38 ?

@matryer @jasonhancock

**Comment by jasonhancock** [comment]
@liilac sorry for the delay...there's now a proposed implementation in https://github.com/graymeta/stow/pull/186
