### ISSUE TITLE
command line tool

### ISSUE THREAD

**Issue by matryer** [graymeta/stow#68]
A command line tool for stow would be quite a powerful addition.

Examples:

```
stow list containers -kind azure -config key="value" key2="value2"
stow add item -container name -kind azure -config etc...
stow download item -container name -kind azure -config etc.... >> file.txt
cat file.txt | stow upload item -container name -kind azure -config etc...
```
- It would go in `github.com/graymeta/stow/cmd/stow`
- The command should rely on no state (which means entire config needs to be passed in each time)

**Comment by TamalSaha** [comment]
Hi, I have build a cli using Stow. You can find it here: https://github.com/appscode/osm
